# encoding: utf-8
# module charset_normalizer.cd
# from C:\Users\T14\PyCharmMiscProject\.venv\Lib\site-packages\charset_normalizer\cd.cp314-win_amd64.pyd
# by generator 1.147
# no doc

# imports
import importlib as importlib # C:\Users\T14\AppData\Local\Programs\Python\Python314\Lib\importlib\__init__.py
from charset_normalizer.md import is_suspiciously_successive_range


# Variables with simple values

LANGUAGE_SUPPORTED_COUNT = 41

TOO_SMALL_SEQUENCE = 32

# functions

def alphabet_languages(*args, **kwargs): # real signature unknown
    pass

def alpha_unicode_split(*args, **kwargs): # real signature unknown
    pass

def characters_popularity_compare(*args, **kwargs): # real signature unknown
    pass

def CoherenceMatches(*args, **kwargs): # real signature unknown
    pass

def coherence_ratio(*args, **kwargs): # real signature unknown
    pass

def encoding_languages(*args, **kwargs): # real signature unknown
    pass

def encoding_unicode_range(*args, **kwargs): # real signature unknown
    pass

def filter_alt_coherence_matches(*args, **kwargs): # real signature unknown
    pass

def get_target_features(*args, **kwargs): # real signature unknown
    pass

def is_accentuated(*args, **kwargs): # real signature unknown
    pass

def is_latin(*args, **kwargs): # real signature unknown
    pass

def is_multi_byte_encoding(*args, **kwargs): # real signature unknown
    """ Verify is a specific encoding is a multi byte one based on it IANA name """
    pass

def is_unicode_range_secondary(*args, **kwargs): # real signature unknown
    pass

def lru_cache(maxsize=128, typed=False): # reliably restored by inspect
    """
    Least-recently-used cache decorator.
    
    If *maxsize* is set to None, the LRU features are disabled and the cache
    can grow without bound.
    
    If *typed* is True, arguments of different types will be cached separately.
    For example, f(decimal.Decimal("3.0")) and f(3.0) will be treated as
    distinct calls with distinct results. Some types such as str and int may
    be cached separately even when typed is false.
    
    Arguments to the cached function must be hashable.
    
    View the cache statistics named tuple (hits, misses, maxsize, currsize)
    with f.cache_info().  Clear the cache and statistics with f.cache_clear().
    Access the underlying function with f.__wrapped__.
    
    See:  https://en.wikipedia.org/wiki/Cache_replacement_policies#Least_recently_used_(LRU)
    """
    pass

def mb_encoding_languages(*args, **kwargs): # real signature unknown
    pass

def merge_coherence_ratios(*args, **kwargs): # real signature unknown
    pass

def TypeCounter(*args, **kwargs): # real signature unknown
    """ A generic version of collections.Counter. """
    pass

def unicode_range(*args, **kwargs): # real signature unknown
    """ Retrieve the Unicode range official name from a single character. """
    pass

def unicode_range_languages(*args, **kwargs): # real signature unknown
    pass

# classes

class Counter(dict):
    """
    Dict subclass for counting hashable items.  Sometimes called a bag
    or multiset.  Elements are stored as dictionary keys and their counts
    are stored as dictionary values.
    
    >>> c = Counter('abcdeabcdabcaba')  # count elements from a string
    
    >>> c.most_common(3)                # three most common elements
    [('a', 5), ('b', 4), ('c', 3)]
    >>> sorted(c)                       # list all unique elements
    ['a', 'b', 'c', 'd', 'e']
    >>> ''.join(sorted(c.elements()))   # list elements with repetitions
    'aaaaabbbbcccdde'
    >>> sum(c.values())                 # total of all counts
    15
    
    >>> c['a']                          # count of letter 'a'
    5
    >>> for elem in 'shazam':           # update counts from an iterable
    ...     c[elem] += 1                # by adding 1 to each element's count
    >>> c['a']                          # now there are seven 'a'
    7
    >>> del c['b']                      # remove all 'b'
    >>> c['b']                          # now there are zero 'b'
    0
    
    >>> d = Counter('simsalabim')       # make another counter
    >>> c.update(d)                     # add in the second counter
    >>> c['a']                          # now there are nine 'a'
    9
    
    >>> c.clear()                       # empty the counter
    >>> c
    Counter()
    
    Note:  If a count is set to zero or reduced to zero, it will remain
    in the counter until the entry is deleted or the counter is cleared:
    
    >>> c = Counter('aaabbc')
    >>> c['b'] -= 2                     # reduce the count of 'b' by two
    >>> c.most_common()                 # 'b' is still in, but its count is zero
    [('a', 3), ('c', 1), ('b', 0)]
    """
    def copy(self): # reliably restored by inspect
        """ Return a shallow copy. """
        pass

    def elements(self): # reliably restored by inspect
        """
        Iterator over elements repeating each as many times as its count.
        
        >>> c = Counter('ABCABC')
        >>> sorted(c.elements())
        ['A', 'A', 'B', 'B', 'C', 'C']
        
        Knuth's example for prime factors of 1836:  2**2 * 3**3 * 17**1
        
        >>> import math
        >>> prime_factors = Counter({2: 2, 3: 3, 17: 1})
        >>> math.prod(prime_factors.elements())
        1836
        
        Note, if an element's count has been set to zero or is a negative
        number, elements() will ignore it.
        """
        pass

    @classmethod
    def fromkeys(cls, *args, **kwargs): # real signature unknown
        pass

    def most_common(self, n=None): # reliably restored by inspect
        """
        List the n most common elements and their counts from the most
        common to the least.  If n is None, then list all element counts.
        
        >>> Counter('abracadabra').most_common(3)
        [('a', 5), ('b', 2), ('r', 2)]
        """
        pass

    def subtract(self, iterable=None, **kwds): # reliably restored by inspect
        """
        Like dict.update() but subtracts counts instead of replacing them.
        Counts can be reduced below zero.  Both the inputs and outputs are
        allowed to contain zero and negative counts.
        
        Source can be an iterable, a dictionary, or another Counter instance.
        
        >>> c = Counter('which')
        >>> c.subtract('witch')             # subtract elements from another iterable
        >>> c.subtract(Counter('watch'))    # subtract elements from another counter
        >>> c['h']                          # 2 in which, minus 1 in witch, minus 1 in watch
        0
        >>> c['w']                          # 1 in which, minus 1 in witch, minus 1 in watch
        -1
        """
        pass

    def total(self): # reliably restored by inspect
        """ Sum of the counts """
        pass

    def update(self, iterable=None, **kwds): # reliably restored by inspect
        """
        Like dict.update() but add counts instead of replacing them.
        
        Source can be an iterable, a dictionary, or another Counter instance.
        
        >>> c = Counter('which')
        >>> c.update('witch')           # add elements from another iterable
        >>> d = Counter('watch')
        >>> c.update(d)                 # add elements from another counter
        >>> c['h']                      # four 'h' in which, witch, and watch
        4
        """
        pass

    def _keep_positive(self): # reliably restored by inspect
        """ Internal method to strip elements with a negative or zero count """
        pass

    def __add__(self, other): # reliably restored by inspect
        """
        Add counts from two counters.
        
        >>> Counter('abbb') + Counter('bcc')
        Counter({'b': 4, 'c': 2, 'a': 1})
        """
        pass

    def __and__(self, other): # reliably restored by inspect
        """
        Intersection is the minimum of corresponding counts.
        
        >>> Counter('abbb') & Counter('bcc')
        Counter({'b': 1})
        """
        pass

    def __delitem__(self, elem): # reliably restored by inspect
        """ Like dict.__delitem__() but does not raise KeyError for missing values. """
        pass

    def __eq__(self, other): # reliably restored by inspect
        """ True if all counts agree. Missing counts are treated as zero. """
        pass

    def __ge__(self, other): # reliably restored by inspect
        """ True if all counts in self are a superset of those in other. """
        pass

    def __gt__(self, other): # reliably restored by inspect
        """ True if all counts in self are a proper superset of those in other. """
        pass

    def __iadd__(self, other): # reliably restored by inspect
        """
        Inplace add from another counter, keeping only positive counts.
        
        >>> c = Counter('abbb')
        >>> c += Counter('bcc')
        >>> c
        Counter({'b': 4, 'c': 2, 'a': 1})
        """
        pass

    def __iand__(self, other): # reliably restored by inspect
        """
        Inplace intersection is the minimum of corresponding counts.
        
        >>> c = Counter('abbb')
        >>> c &= Counter('bcc')
        >>> c
        Counter({'b': 1})
        """
        pass

    def __init__(self, iterable=None, **kwds): # reliably restored by inspect
        """
        Create a new, empty Counter object.  And if given, count elements
        from an input iterable.  Or, initialize the count from another mapping
        of elements to their counts.
        
        >>> c = Counter()                           # a new, empty counter
        >>> c = Counter('gallahad')                 # a new counter from an iterable
        >>> c = Counter({'a': 4, 'b': 2})           # a new counter from a mapping
        >>> c = Counter(a=4, b=2)                   # a new counter from keyword args
        """
        pass

    def __ior__(self, other): # reliably restored by inspect
        """
        Inplace union is the maximum of value from either counter.
        
        >>> c = Counter('abbb')
        >>> c |= Counter('bcc')
        >>> c
        Counter({'b': 3, 'c': 2, 'a': 1})
        """
        pass

    def __isub__(self, other): # reliably restored by inspect
        """
        Inplace subtract counter, but keep only results with positive counts.
        
        >>> c = Counter('abbbc')
        >>> c -= Counter('bccd')
        >>> c
        Counter({'b': 2, 'a': 1})
        """
        pass

    def __le__(self, other): # reliably restored by inspect
        """ True if all counts in self are a subset of those in other. """
        pass

    def __lt__(self, other): # reliably restored by inspect
        """ True if all counts in self are a proper subset of those in other. """
        pass

    def __missing__(self, key): # reliably restored by inspect
        """ The count of elements not in the Counter is zero. """
        pass

    def __neg__(self): # reliably restored by inspect
        """
        Subtracts from an empty counter.  Strips positive and zero counts,
        and flips the sign on negative counts.
        """
        pass

    def __ne__(self, other): # reliably restored by inspect
        """ True if any counts disagree. Missing counts are treated as zero. """
        pass

    def __or__(self, other): # reliably restored by inspect
        """
        Union is the maximum of value in either of the input counters.
        
        >>> Counter('abbb') | Counter('bcc')
        Counter({'b': 3, 'c': 2, 'a': 1})
        """
        pass

    def __pos__(self): # reliably restored by inspect
        """ Adds an empty counter, effectively stripping negative and zero counts """
        pass

    def __reduce__(self): # reliably restored by inspect
        # no doc
        pass

    def __repr__(self): # reliably restored by inspect
        # no doc
        pass

    def __sub__(self, other): # reliably restored by inspect
        """
        Subtract count, but keep only results with positive counts.
        
        >>> Counter('abbbc') - Counter('bccd')
        Counter({'b': 2, 'a': 1})
        """
        pass

    __weakref__ = property(lambda self: object(), lambda self, v: None, lambda self: None)  # default
    """list of weak references to the object"""


    __dict__ = None # (!) real value is 'mappingproxy({\'__module__\': \'collections\', \'__firstlineno__\': 551, \'__doc__\': "Dict subclass for counting hashable items.  Sometimes called a bag\\nor multiset.  Elements are stored as dictionary keys and their counts\\nare stored as dictionary values.\\n\\n>>> c = Counter(\'abcdeabcdabcaba\')  # count elements from a string\\n\\n>>> c.most_common(3)                # three most common elements\\n[(\'a\', 5), (\'b\', 4), (\'c\', 3)]\\n>>> sorted(c)                       # list all unique elements\\n[\'a\', \'b\', \'c\', \'d\', \'e\']\\n>>> \'\'.join(sorted(c.elements()))   # list elements with repetitions\\n\'aaaaabbbbcccdde\'\\n>>> sum(c.values())                 # total of all counts\\n15\\n\\n>>> c[\'a\']                          # count of letter \'a\'\\n5\\n>>> for elem in \'shazam\':           # update counts from an iterable\\n...     c[elem] += 1                # by adding 1 to each element\'s count\\n>>> c[\'a\']                          # now there are seven \'a\'\\n7\\n>>> del c[\'b\']                      # remove all \'b\'\\n>>> c[\'b\']                          # now there are zero \'b\'\\n0\\n\\n>>> d = Counter(\'simsalabim\')       # make another counter\\n>>> c.update(d)                     # add in the second counter\\n>>> c[\'a\']                          # now there are nine \'a\'\\n9\\n\\n>>> c.clear()                       # empty the counter\\n>>> c\\nCounter()\\n\\nNote:  If a count is set to zero or reduced to zero, it will remain\\nin the counter until the entry is deleted or the counter is cleared:\\n\\n>>> c = Counter(\'aaabbc\')\\n>>> c[\'b\'] -= 2                     # reduce the count of \'b\' by two\\n>>> c.most_common()                 # \'b\' is still in, but its count is zero\\n[(\'a\', 3), (\'c\', 1), (\'b\', 0)]\\n\\n", \'__init__\': <function Counter.__init__ at 0x000001C889EDDD20>, \'__missing__\': <function Counter.__missing__ at 0x000001C889F1C040>, \'total\': <function Counter.total at 0x000001C889F1C0F0>, \'most_common\': <function Counter.most_common at 0x000001C889F1C1A0>, \'elements\': <function Counter.elements at 0x000001C889F1C250>, \'fromkeys\': <classmethod(<function Counter.fromkeys at 0x000001C889F1C300>)>, \'update\': <function Counter.update at 0x000001C889F1C3B0>, \'subtract\': <function Counter.subtract at 0x000001C889F1C460>, \'copy\': <function Counter.copy at 0x000001C889F1C510>, \'__reduce__\': <function Counter.__reduce__ at 0x000001C889F1C5C0>, \'__delitem__\': <function Counter.__delitem__ at 0x000001C889F1C670>, \'__repr__\': <function Counter.__repr__ at 0x000001C889F1C720>, \'__eq__\': <function Counter.__eq__ at 0x000001C889F1C7D0>, \'__ne__\': <function Counter.__ne__ at 0x000001C889F1C880>, \'__le__\': <function Counter.__le__ at 0x000001C889F1C930>, \'__lt__\': <function Counter.__lt__ at 0x000001C889F1C9E0>, \'__ge__\': <function Counter.__ge__ at 0x000001C889F1CA90>, \'__gt__\': <function Counter.__gt__ at 0x000001C889F1CB40>, \'__add__\': <function Counter.__add__ at 0x000001C889F1CBF0>, \'__sub__\': <function Counter.__sub__ at 0x000001C889F1CCA0>, \'__or__\': <function Counter.__or__ at 0x000001C889F1CD50>, \'__and__\': <function Counter.__and__ at 0x000001C889F1CE00>, \'__pos__\': <function Counter.__pos__ at 0x000001C889F1CEB0>, \'__neg__\': <function Counter.__neg__ at 0x000001C889F1CF60>, \'_keep_positive\': <function Counter._keep_positive at 0x000001C889F1D010>, \'__iadd__\': <function Counter.__iadd__ at 0x000001C889F1D0C0>, \'__isub__\': <function Counter.__isub__ at 0x000001C889F1D170>, \'__ior__\': <function Counter.__ior__ at 0x000001C889F1D220>, \'__iand__\': <function Counter.__iand__ at 0x000001C889F1D2D0>, \'__static_attributes__\': (), \'__dict__\': <attribute \'__dict__\' of \'Counter\' objects>, \'__weakref__\': <attribute \'__weakref__\' of \'Counter\' objects>, \'__hash__\': None})'
    __firstlineno__ = 551
    __hash__ = None
    __static_attributes__ = ()


class IncrementalDecoder(object):
    """
    An IncrementalDecoder decodes an input in multiple steps. The input can
    be passed piece by piece to the decode() method. The IncrementalDecoder
    remembers the state of the decoding process between calls to decode().
    """
    def decode(self, input, final=False): # reliably restored by inspect
        """ Decode input and returns the resulting object. """
        pass

    def getstate(self): # reliably restored by inspect
        """
        Return the current state of the decoder.
        
        This must be a (buffered_input, additional_state_info) tuple.
        buffered_input must be a bytes object containing bytes that
        were passed to decode() that have not yet been converted.
        additional_state_info must be a non-negative integer
        representing the state of the decoder WITHOUT yet having
        processed the contents of buffered_input.  In the initial state
        and after reset(), getstate() must return (b"", 0).
        """
        pass

    def reset(self): # reliably restored by inspect
        """ Reset the decoder to the initial state. """
        pass

    def setstate(self, state): # reliably restored by inspect
        """
        Set the current state of the decoder.
        
        state must have been returned by getstate().  The effect of
        setstate((b"", 0)) must be equivalent to reset().
        """
        pass

    def __init__(self, errors=None): # reliably restored by inspect
        """
        Create an IncrementalDecoder instance.
        
        The IncrementalDecoder may use different error handling schemes by
        providing the errors keyword argument. See the module docstring
        for a list of possible values.
        """
        pass

    __weakref__ = property(lambda self: object(), lambda self, v: None, lambda self: None)  # default
    """list of weak references to the object"""


    __dict__ = None # (!) real value is "mappingproxy({'__module__': 'codecs', '__firstlineno__': 257, '__doc__': '\\nAn IncrementalDecoder decodes an input in multiple steps. The input can\\nbe passed piece by piece to the decode() method. The IncrementalDecoder\\nremembers the state of the decoding process between calls to decode().\\n', '__init__': <function IncrementalDecoder.__init__ at 0x000001C889E33D70>, 'decode': <function IncrementalDecoder.decode at 0x000001C889E33E20>, 'reset': <function IncrementalDecoder.reset at 0x000001C889E33ED0>, 'getstate': <function IncrementalDecoder.getstate at 0x000001C889E5C040>, 'setstate': <function IncrementalDecoder.setstate at 0x000001C889E5C0F0>, '__static_attributes__': ('errors',), '__dict__': <attribute '__dict__' of 'IncrementalDecoder' objects>, '__weakref__': <attribute '__weakref__' of 'IncrementalDecoder' objects>})"
    __firstlineno__ = 257
    __static_attributes__ = (
        'errors',
    )


# variables with complex values

annotations = None # (!) real value is "_Feature((3, 7, 0, 'beta', 1), None, 16777216)"

FREQUENCIES = {
    'Arabic': [
        'ا',
        'ل',
        'ي',
        'م',
        'و',
        'ن',
        'ر',
        'ت',
        'ب',
        'ة',
        'ع',
        'د',
        'س',
        'ف',
        'ه',
        'ك',
        'ق',
        'أ',
        'ح',
        'ج',
        'ش',
        'ط',
        'ص',
        'ى',
        'خ',
        'إ',
    ],
    'Bulgarian': [
        'а',
        'и',
        'о',
        'е',
        'н',
        'т',
        'р',
        'с',
        'в',
        'л',
        'к',
        'д',
        'п',
        'м',
        'з',
        'г',
        'я',
        'ъ',
        'у',
        'б',
        'ч',
        'ц',
        'й',
        'ж',
        'щ',
        'х',
    ],
    'Chinese': [
        '的',
        '一',
        '是',
        '不',
        '了',
        '在',
        '人',
        '有',
        '我',
        '他',
        '这',
        '个',
        '们',
        '中',
        '来',
        '上',
        '大',
        '为',
        '和',
        '国',
        '地',
        '到',
        '以',
        '说',
        '时',
        '要',
        '就',
        '出',
        '会',
        '可',
        '也',
        '你',
        '对',
        '生',
        '能',
        '而',
        '子',
        '那',
        '得',
        '于',
        '着',
        '下',
        '自',
        '之',
        '年',
        '过',
        '发',
        '后',
        '作',
        '里',
        '用',
        '道',
        '行',
        '所',
        '然',
        '家',
        '种',
        '事',
        '成',
        '方',
        '多',
        '经',
        '么',
        '去',
        '法',
        '学',
        '如',
        '都',
        '同',
        '现',
        '当',
        '没',
        '动',
        '面',
        '起',
        '看',
        '定',
        '天',
        '分',
        '还',
        '进',
        '好',
        '小',
        '部',
        '其',
        '些',
        '主',
        '样',
        '理',
        '心',
        '她',
        '本',
        '前',
        '开',
        '但',
        '因',
        '只',
        '从',
        '想',
        '实',
    ],
    'Croatian': [
        'a',
        'i',
        'o',
        'e',
        'n',
        'r',
        'j',
        's',
        't',
        'u',
        'k',
        'l',
        'v',
        'd',
        'm',
        'p',
        'g',
        'z',
        'b',
        'c',
        'č',
        'h',
        'š',
        'ž',
        'ć',
        'f',
    ],
    'Czech': [
        'o',
        'e',
        'a',
        'n',
        't',
        's',
        'i',
        'l',
        'v',
        'r',
        'k',
        'd',
        'u',
        'm',
        'p',
        'í',
        'c',
        'h',
        'z',
        'á',
        'y',
        'j',
        'b',
        'ě',
        'é',
        'ř',
    ],
    'Danish': [
        'e',
        'r',
        'n',
        't',
        'a',
        'i',
        's',
        'd',
        'l',
        'o',
        'g',
        'm',
        'k',
        'f',
        'v',
        'u',
        'b',
        'h',
        'p',
        'å',
        'y',
        'ø',
        'æ',
        'c',
        'j',
        'w',
    ],
    'Dutch': [
        'e',
        'n',
        'a',
        'i',
        'r',
        't',
        'o',
        'd',
        's',
        'l',
        'g',
        'h',
        'v',
        'm',
        'u',
        'k',
        'c',
        'p',
        'b',
        'w',
        'j',
        'z',
        'f',
        'y',
        'x',
        'ë',
    ],
    'English': [
        'e',
        'a',
        't',
        'i',
        'o',
        'n',
        's',
        'r',
        'h',
        'l',
        'd',
        'c',
        'u',
        'm',
        'f',
        'p',
        'g',
        'w',
        'y',
        'b',
        'v',
        'k',
        'x',
        'j',
        'z',
        'q',
    ],
    'English—': [
        'e',
        'a',
        't',
        'i',
        'o',
        'n',
        's',
        'r',
        'h',
        'l',
        'd',
        'c',
        'm',
        'u',
        'f',
        'p',
        'g',
        'w',
        'b',
        'y',
        'v',
        'k',
        'j',
        'x',
        'z',
        'q',
    ],
    'Estonian': [
        'a',
        'i',
        'e',
        's',
        't',
        'l',
        'u',
        'n',
        'o',
        'k',
        'r',
        'd',
        'm',
        'v',
        'g',
        'p',
        'j',
        'h',
        'ä',
        'b',
        'õ',
        'ü',
        'f',
        'c',
        'ö',
        'y',
    ],
    'Farsi': [
        'ا',
        'ی',
        'ر',
        'د',
        'ن',
        'ه',
        'و',
        'م',
        'ت',
        'ب',
        'س',
        'ل',
        'ک',
        'ش',
        'ز',
        'ف',
        'گ',
        'ع',
        'خ',
        'ق',
        'ج',
        'آ',
        'پ',
        'ح',
        'ط',
        'ص',
    ],
    'Finnish': [
        'a',
        'i',
        'n',
        't',
        'e',
        's',
        'l',
        'o',
        'u',
        'k',
        'ä',
        'm',
        'r',
        'v',
        'j',
        'h',
        'p',
        'y',
        'd',
        'ö',
        'g',
        'c',
        'b',
        'f',
        'w',
        'z',
    ],
    'French': [
        'e',
        'a',
        's',
        'n',
        'i',
        't',
        'r',
        'l',
        'u',
        'o',
        'd',
        'c',
        'p',
        'm',
        'é',
        'v',
        'g',
        'f',
        'b',
        'h',
        'q',
        'à',
        'x',
        'è',
        'y',
        'j',
    ],
    'German': [
        'e',
        'n',
        'i',
        'r',
        's',
        't',
        'a',
        'd',
        'h',
        'u',
        'l',
        'g',
        'o',
        'c',
        'm',
        'b',
        'f',
        'k',
        'w',
        'z',
        'p',
        'v',
        'ü',
        'ä',
        'ö',
        'j',
    ],
    'Greek': [
        'α',
        'τ',
        'ο',
        'ι',
        'ε',
        'ν',
        'ρ',
        'σ',
        'κ',
        'η',
        'π',
        'ς',
        'υ',
        'μ',
        'λ',
        'ί',
        'ό',
        'ά',
        'γ',
        'έ',
        'δ',
        'ή',
        'ω',
        'χ',
        'θ',
        'ύ',
    ],
    'Hebrew': [
        'י',
        'ו',
        'ה',
        'ל',
        'ר',
        'ב',
        'ת',
        'מ',
        'א',
        'ש',
        'נ',
        'ע',
        'ם',
        'ד',
        'ק',
        'ח',
        'פ',
        'ס',
        'כ',
        'ג',
        'ט',
        'צ',
        'ן',
        'ז',
        'ך',
    ],
    'Hindi': [
        'क',
        'र',
        'स',
        'न',
        'त',
        'म',
        'ह',
        'प',
        'य',
        'ल',
        'व',
        'ज',
        'द',
        'ग',
        'ब',
        'श',
        'ट',
        'अ',
        'ए',
        'थ',
        'भ',
        'ड',
        'च',
        'ध',
        'ष',
        'इ',
    ],
    'Hungarian': [
        'e',
        'a',
        't',
        'l',
        's',
        'n',
        'k',
        'r',
        'i',
        'o',
        'z',
        'á',
        'é',
        'g',
        'm',
        'b',
        'y',
        'v',
        'd',
        'h',
        'u',
        'p',
        'j',
        'ö',
        'f',
        'c',
    ],
    'Indonesian': [
        'a',
        'n',
        'e',
        'i',
        'r',
        't',
        'u',
        's',
        'd',
        'k',
        'm',
        'l',
        'g',
        'p',
        'b',
        'o',
        'h',
        'y',
        'j',
        'c',
        'w',
        'f',
        'v',
        'z',
        'x',
        'q',
    ],
    'Italian': [
        'e',
        'i',
        'a',
        'o',
        'n',
        'l',
        't',
        'r',
        's',
        'c',
        'd',
        'u',
        'p',
        'm',
        'g',
        'v',
        'f',
        'b',
        'z',
        'h',
        'q',
        'è',
        'à',
        'k',
        'y',
        'ò',
    ],
    'Japanese': [
        '日',
        '一',
        '人',
        '年',
        '大',
        '十',
        '二',
        '本',
        '中',
        '長',
        '出',
        '三',
        '時',
        '行',
        '見',
        '月',
        '分',
        '後',
        '前',
        '生',
        '五',
        '間',
        '上',
        '東',
        '四',
        '今',
        '金',
        '九',
        '入',
        '学',
        '高',
        '円',
        '子',
        '外',
        '八',
        '六',
        '下',
        '来',
        '気',
        '小',
        '七',
        '山',
        '話',
        '女',
        '北',
        '午',
        '百',
        '書',
        '先',
        '名',
        '川',
        '千',
        '水',
        '半',
        '男',
        '西',
        '電',
        '校',
        '語',
        '土',
        '木',
        '聞',
        '食',
        '車',
        '何',
        '南',
        '万',
        '毎',
        '白',
        '天',
        '母',
        '火',
        '右',
        '読',
        '友',
        '左',
        '休',
        '父',
        '雨',
    ],
    'Japanese—': [
        'ー',
        'ン',
        'ス',
        '・',
        'ル',
        'ト',
        'リ',
        'イ',
        'ア',
        'ラ',
        'ッ',
        'ク',
        'ド',
        'シ',
        'レ',
        'ジ',
        'タ',
        'フ',
        'ロ',
        'カ',
        'テ',
        'マ',
        'ィ',
        'グ',
        'バ',
        'ム',
        'プ',
        'オ',
        'コ',
        'デ',
        'ニ',
        'ウ',
        'メ',
        'サ',
        'ビ',
        'ナ',
        'ブ',
        'ャ',
        'エ',
        'ュ',
        'チ',
        'キ',
        'ズ',
        'ダ',
        'パ',
        'ミ',
        'ェ',
        'ョ',
        'ハ',
        'セ',
        'ベ',
        'ガ',
        'モ',
        'ツ',
        'ネ',
        'ボ',
        'ソ',
        'ノ',
        'ァ',
        'ヴ',
        'ワ',
        'ポ',
        'ペ',
        'ピ',
        'ケ',
        'ゴ',
        'ギ',
        'ザ',
        'ホ',
        'ゲ',
        'ォ',
        'ヤ',
        'ヒ',
        'ユ',
        'ヨ',
        'ヘ',
        'ゼ',
        'ヌ',
        'ゥ',
        'ゾ',
        'ヶ',
        'ヂ',
        'ヲ',
        'ヅ',
        'ヵ',
        'ヱ',
        'ヰ',
        'ヮ',
        'ヽ',
        '゠',
        'ヾ',
        'ヷ',
        'ヿ',
        'ヸ',
        'ヹ',
        'ヺ',
    ],
    'Japanese——': [
        'の',
        'に',
        'る',
        'た',
        'と',
        'は',
        'し',
        'い',
        'を',
        'で',
        'て',
        'が',
        'な',
        'れ',
        'か',
        'ら',
        'さ',
        'っ',
        'り',
        'す',
        'あ',
        'も',
        'こ',
        'ま',
        'う',
        'く',
        'よ',
        'き',
        'ん',
        'め',
        'お',
        'け',
        'そ',
        'つ',
        'だ',
        'や',
        'え',
        'ど',
        'わ',
        'ち',
        'み',
        'せ',
        'じ',
        'ば',
        'へ',
        'び',
        'ず',
        'ろ',
        'ほ',
        'げ',
        'む',
        'べ',
        'ひ',
        'ょ',
        'ゆ',
        'ぶ',
        'ご',
        'ゃ',
        'ね',
        'ふ',
        'ぐ',
        'ぎ',
        'ぼ',
        'ゅ',
        'づ',
        'ざ',
        'ぞ',
        'ぬ',
        'ぜ',
        'ぱ',
        'ぽ',
        'ぷ',
        'ぴ',
        'ぃ',
        'ぁ',
        'ぇ',
        'ぺ',
        'ゞ',
        'ぢ',
        'ぉ',
        'ぅ',
        'ゐ',
        'ゝ',
        'ゑ',
        '゛',
        '゜',
        'ゎ',
        'ゔ',
        '゚',
        'ゟ',
        '゙',
        'ゕ',
        'ゖ',
    ],
    'Kazakh': [
        'а',
        'ы',
        'е',
        'н',
        'т',
        'р',
        'л',
        'і',
        'д',
        'с',
        'м',
        'қ',
        'к',
        'о',
        'б',
        'и',
        'у',
        'ғ',
        'ж',
        'ң',
        'з',
        'ш',
        'й',
        'п',
        'г',
        'ө',
    ],
    'Korean': [
        '이',
        '다',
        '에',
        '의',
        '는',
        '로',
        '하',
        '을',
        '가',
        '고',
        '지',
        '서',
        '한',
        '은',
        '기',
        '으',
        '년',
        '대',
        '사',
        '시',
        '를',
        '리',
        '도',
        '인',
        '스',
        '일',
    ],
    'Lithuanian': [
        'i',
        'a',
        's',
        'o',
        'r',
        'e',
        't',
        'n',
        'u',
        'k',
        'm',
        'l',
        'p',
        'v',
        'd',
        'j',
        'g',
        'ė',
        'b',
        'y',
        'ų',
        'š',
        'ž',
        'c',
        'ą',
        'į',
    ],
    'Norwegian': [
        'e',
        'r',
        'n',
        't',
        'a',
        's',
        'i',
        'o',
        'l',
        'd',
        'g',
        'k',
        'm',
        'v',
        'f',
        'p',
        'u',
        'b',
        'h',
        'å',
        'y',
        'j',
        'ø',
        'c',
        'æ',
        'w',
    ],
    'Polish': [
        'a',
        'i',
        'o',
        'e',
        'n',
        'r',
        'z',
        'w',
        's',
        'c',
        't',
        'k',
        'y',
        'd',
        'p',
        'm',
        'u',
        'l',
        'j',
        'ł',
        'g',
        'b',
        'h',
        'ą',
        'ę',
        'ó',
    ],
    'Portuguese': [
        'a',
        'e',
        'o',
        's',
        'i',
        'r',
        'd',
        'n',
        't',
        'm',
        'u',
        'c',
        'l',
        'p',
        'g',
        'v',
        'b',
        'f',
        'h',
        'ã',
        'q',
        'é',
        'ç',
        'á',
        'z',
        'í',
    ],
    'Romanian': [
        'e',
        'i',
        'a',
        'r',
        'n',
        't',
        'u',
        'l',
        'o',
        'c',
        's',
        'd',
        'p',
        'm',
        'ă',
        'f',
        'v',
        'î',
        'g',
        'b',
        'ș',
        'ț',
        'z',
        'h',
        'â',
        'j',
    ],
    'Russian': [
        'о',
        'е',
        'а',
        'и',
        'н',
        'т',
        'с',
        'р',
        'в',
        'л',
        'к',
        'м',
        'д',
        'п',
        'у',
        'г',
        'я',
        'ы',
        'з',
        'б',
        'й',
        'ь',
        'ч',
        'х',
        'ж',
        'ц',
    ],
    'Serbian': [
        'а',
        'и',
        'о',
        'е',
        'н',
        'р',
        'с',
        'у',
        'т',
        'к',
        'ј',
        'в',
        'д',
        'м',
        'п',
        'л',
        'г',
        'з',
        'б',
        'a',
        'i',
        'e',
        'o',
        'n',
        'ц',
        'ш',
    ],
    'Slovak': [
        'o',
        'a',
        'e',
        'n',
        'i',
        'r',
        'v',
        't',
        's',
        'l',
        'k',
        'd',
        'm',
        'p',
        'u',
        'c',
        'h',
        'j',
        'b',
        'z',
        'á',
        'y',
        'ý',
        'í',
        'č',
        'é',
    ],
    'Slovene': [
        'e',
        'a',
        'i',
        'o',
        'n',
        'r',
        's',
        'l',
        't',
        'j',
        'v',
        'k',
        'd',
        'p',
        'm',
        'u',
        'z',
        'b',
        'g',
        'h',
        'č',
        'c',
        'š',
        'ž',
        'f',
        'y',
    ],
    'Spanish': [
        'e',
        'a',
        'o',
        'n',
        's',
        'r',
        'i',
        'l',
        'd',
        't',
        'c',
        'u',
        'm',
        'p',
        'b',
        'g',
        'v',
        'f',
        'y',
        'ó',
        'h',
        'q',
        'í',
        'j',
        'z',
        'á',
    ],
    'Swedish': [
        'e',
        'a',
        'n',
        'r',
        't',
        's',
        'i',
        'l',
        'd',
        'o',
        'm',
        'k',
        'g',
        'v',
        'h',
        'f',
        'u',
        'p',
        'ä',
        'c',
        'b',
        'ö',
        'å',
        'y',
        'j',
        'x',
    ],
    'Tamil': [
        'க',
        'த',
        'ப',
        'ட',
        'ர',
        'ம',
        'ல',
        'ன',
        'வ',
        'ற',
        'ய',
        'ள',
        'ச',
        'ந',
        'இ',
        'ண',
        'அ',
        'ஆ',
        'ழ',
        'ங',
        'எ',
        'உ',
        'ஒ',
        'ஸ',
    ],
    'Thai': [
        'า',
        'น',
        'ร',
        'อ',
        'ก',
        'เ',
        'ง',
        'ม',
        'ย',
        'ล',
        'ว',
        'ด',
        'ท',
        'ส',
        'ต',
        'ะ',
        'ป',
        'บ',
        'ค',
        'ห',
        'แ',
        'จ',
        'พ',
        'ช',
        'ข',
        'ใ',
    ],
    'Turkish': [
        'a',
        'e',
        'i',
        'n',
        'r',
        'l',
        'ı',
        'k',
        'd',
        't',
        's',
        'm',
        'y',
        'u',
        'o',
        'b',
        'ü',
        'ş',
        'v',
        'g',
        'z',
        'h',
        'c',
        'p',
        'ç',
        'ğ',
    ],
    'Ukrainian': [
        'о',
        'а',
        'н',
        'і',
        'и',
        'р',
        'в',
        'т',
        'е',
        'с',
        'к',
        'л',
        'у',
        'д',
        'м',
        'п',
        'з',
        'я',
        'ь',
        'б',
        'г',
        'й',
        'ч',
        'х',
        'ц',
        'ї',
    ],
    'Vietnamese': [
        'n',
        'h',
        't',
        'i',
        'c',
        'g',
        'a',
        'o',
        'u',
        'm',
        'l',
        'r',
        'à',
        'đ',
        's',
        'e',
        'v',
        'p',
        'b',
        'y',
        'ư',
        'd',
        'á',
        'k',
        'ộ',
        'ế',
    ],
}

KO_NAMES = None # (!) real value is "frozenset({'euc_kr', 'cp949', 'johab'})"

ZH_NAMES = None # (!) real value is "frozenset({'big5', 'cp950', 'hz', 'big5hkscs'})"

_FREQUENCIES_RANK = {
    'Arabic': {
        'أ': 17,
        'إ': 25,
        'ا': 0,
        'ب': 8,
        'ة': 9,
        'ت': 7,
        'ج': 19,
        'ح': 18,
        'خ': 24,
        'د': 11,
        'ر': 6,
        'س': 12,
        'ش': 20,
        'ص': 22,
        'ط': 21,
        'ع': 10,
        'ف': 13,
        'ق': 16,
        'ك': 15,
        'ل': 1,
        'م': 3,
        'ن': 5,
        'ه': 14,
        'و': 4,
        'ى': 23,
        'ي': 2,
    },
    'Bulgarian': {
        'а': 0,
        'б': 19,
        'в': 8,
        'г': 15,
        'д': 11,
        'е': 3,
        'ж': 23,
        'з': 14,
        'и': 1,
        'й': 22,
        'к': 10,
        'л': 9,
        'м': 13,
        'н': 4,
        'о': 2,
        'п': 12,
        'р': 6,
        'с': 7,
        'т': 5,
        'у': 18,
        'х': 25,
        'ц': 21,
        'ч': 20,
        'щ': 24,
        'ъ': 17,
        'я': 16,
    },
    'Chinese': {
        '一': 1,
        '上': 15,
        '下': 41,
        '不': 3,
        '个': 11,
        '中': 13,
        '为': 17,
        '主': 86,
        '么': 62,
        '之': 43,
        '也': 30,
        '了': 4,
        '事': 57,
        '于': 39,
        '些': 85,
        '人': 6,
        '从': 97,
        '他': 9,
        '以': 22,
        '们': 12,
        '会': 28,
        '但': 94,
        '作': 48,
        '你': 31,
        '其': 84,
        '出': 27,
        '分': 78,
        '到': 21,
        '前': 92,
        '动': 72,
        '去': 63,
        '发': 46,
        '只': 96,
        '可': 29,
        '同': 68,
        '后': 47,
        '和': 18,
        '因': 95,
        '国': 19,
        '在': 5,
        '地': 20,
        '多': 60,
        '大': 16,
        '天': 77,
        '她': 90,
        '好': 81,
        '如': 66,
        '子': 36,
        '学': 65,
        '定': 76,
        '实': 99,
        '家': 55,
        '对': 32,
        '小': 82,
        '就': 26,
        '年': 44,
        '开': 93,
        '当': 70,
        '得': 38,
        '心': 89,
        '想': 98,
        '成': 58,
        '我': 8,
        '所': 53,
        '方': 59,
        '时': 24,
        '是': 2,
        '有': 7,
        '本': 91,
        '来': 14,
        '样': 87,
        '没': 71,
        '法': 64,
        '然': 54,
        '现': 69,
        '理': 88,
        '生': 33,
        '用': 50,
        '的': 0,
        '看': 75,
        '着': 40,
        '种': 56,
        '经': 61,
        '而': 35,
        '能': 34,
        '自': 42,
        '行': 52,
        '要': 25,
        '说': 23,
        '起': 74,
        '过': 45,
        '还': 79,
        '这': 10,
        '进': 80,
        '道': 51,
        '那': 37,
        '部': 83,
        '都': 67,
        '里': 49,
        '面': 73,
    },
    'Croatian': {
        'a': 0,
        'b': 18,
        'c': 19,
        'd': 13,
        'e': 3,
        'f': 25,
        'g': 16,
        'h': 21,
        'i': 1,
        'j': 6,
        'k': 10,
        'l': 11,
        'm': 14,
        'n': 4,
        'o': 2,
        'p': 15,
        'r': 5,
        's': 7,
        't': 8,
        'u': 9,
        'v': 12,
        'z': 17,
        'ć': 24,
        'č': 20,
        'š': 22,
        'ž': 23,
    },
    'Czech': {
        'a': 2,
        'b': 22,
        'c': 16,
        'd': 11,
        'e': 1,
        'h': 17,
        'i': 6,
        'j': 21,
        'k': 10,
        'l': 7,
        'm': 13,
        'n': 3,
        'o': 0,
        'p': 14,
        'r': 9,
        's': 5,
        't': 4,
        'u': 12,
        'v': 8,
        'y': 20,
        'z': 18,
        'á': 19,
        'é': 24,
        'í': 15,
        'ě': 23,
        'ř': 25,
    },
    'Danish': {
        'a': 4,
        'b': 16,
        'c': 23,
        'd': 7,
        'e': 0,
        'f': 13,
        'g': 10,
        'h': 17,
        'i': 5,
        'j': 24,
        'k': 12,
        'l': 8,
        'm': 11,
        'n': 2,
        'o': 9,
        'p': 18,
        'r': 1,
        's': 6,
        't': 3,
        'u': 15,
        'v': 14,
        'w': 25,
        'y': 20,
        'å': 19,
        'æ': 22,
        'ø': 21,
    },
    'Dutch': {
        'a': 2,
        'b': 18,
        'c': 16,
        'd': 7,
        'e': 0,
        'f': 22,
        'g': 10,
        'h': 11,
        'i': 3,
        'j': 20,
        'k': 15,
        'l': 9,
        'm': 13,
        'n': 1,
        'o': 6,
        'p': 17,
        'r': 4,
        's': 8,
        't': 5,
        'u': 14,
        'v': 12,
        'w': 19,
        'x': 24,
        'y': 23,
        'z': 21,
        'ë': 25,
    },
    'English': {
        'a': 1,
        'b': 19,
        'c': 11,
        'd': 10,
        'e': 0,
        'f': 14,
        'g': 16,
        'h': 8,
        'i': 3,
        'j': 23,
        'k': 21,
        'l': 9,
        'm': 13,
        'n': 5,
        'o': 4,
        'p': 15,
        'q': 25,
        'r': 7,
        's': 6,
        't': 2,
        'u': 12,
        'v': 20,
        'w': 17,
        'x': 22,
        'y': 18,
        'z': 24,
    },
    'English—': {
        'a': 1,
        'b': 18,
        'c': 11,
        'd': 10,
        'e': 0,
        'f': 14,
        'g': 16,
        'h': 8,
        'i': 3,
        'j': 22,
        'k': 21,
        'l': 9,
        'm': 12,
        'n': 5,
        'o': 4,
        'p': 15,
        'q': 25,
        'r': 7,
        's': 6,
        't': 2,
        'u': 13,
        'v': 20,
        'w': 17,
        'x': 23,
        'y': 19,
        'z': 24,
    },
    'Estonian': {
        'a': 0,
        'b': 19,
        'c': 23,
        'd': 11,
        'e': 2,
        'f': 22,
        'g': 14,
        'h': 17,
        'i': 1,
        'j': 16,
        'k': 9,
        'l': 5,
        'm': 12,
        'n': 7,
        'o': 8,
        'p': 15,
        'r': 10,
        's': 3,
        't': 4,
        'u': 6,
        'v': 13,
        'y': 25,
        'ä': 18,
        'õ': 20,
        'ö': 24,
        'ü': 21,
    },
    'Farsi': {
        'آ': 21,
        'ا': 0,
        'ب': 9,
        'ت': 8,
        'ج': 20,
        'ح': 23,
        'خ': 18,
        'د': 3,
        'ر': 2,
        'ز': 14,
        'س': 10,
        'ش': 13,
        'ص': 25,
        'ط': 24,
        'ع': 17,
        'ف': 15,
        'ق': 19,
        'ل': 11,
        'م': 7,
        'ن': 4,
        'ه': 5,
        'و': 6,
        'پ': 22,
        'ک': 12,
        'گ': 16,
        'ی': 1,
    },
    'Finnish': {
        'a': 0,
        'b': 22,
        'c': 21,
        'd': 18,
        'e': 4,
        'f': 23,
        'g': 20,
        'h': 15,
        'i': 1,
        'j': 14,
        'k': 9,
        'l': 6,
        'm': 11,
        'n': 2,
        'o': 7,
        'p': 16,
        'r': 12,
        's': 5,
        't': 3,
        'u': 8,
        'v': 13,
        'w': 24,
        'y': 17,
        'z': 25,
        'ä': 10,
        'ö': 19,
    },
    'French': {
        'a': 1,
        'b': 18,
        'c': 11,
        'd': 10,
        'e': 0,
        'f': 17,
        'g': 16,
        'h': 19,
        'i': 4,
        'j': 25,
        'l': 7,
        'm': 13,
        'n': 3,
        'o': 9,
        'p': 12,
        'q': 20,
        'r': 6,
        's': 2,
        't': 5,
        'u': 8,
        'v': 15,
        'x': 22,
        'y': 24,
        'à': 21,
        'è': 23,
        'é': 14,
    },
    'German': {
        'a': 6,
        'b': 15,
        'c': 13,
        'd': 7,
        'e': 0,
        'f': 16,
        'g': 11,
        'h': 8,
        'i': 2,
        'j': 25,
        'k': 17,
        'l': 10,
        'm': 14,
        'n': 1,
        'o': 12,
        'p': 20,
        'r': 3,
        's': 4,
        't': 5,
        'u': 9,
        'v': 21,
        'w': 18,
        'z': 19,
        'ä': 23,
        'ö': 24,
        'ü': 22,
    },
    'Greek': {
        'ά': 17,
        'έ': 19,
        'ή': 21,
        'ί': 15,
        'α': 0,
        'γ': 18,
        'δ': 20,
        'ε': 4,
        'η': 9,
        'θ': 24,
        'ι': 3,
        'κ': 8,
        'λ': 14,
        'μ': 13,
        'ν': 5,
        'ο': 2,
        'π': 10,
        'ρ': 6,
        'ς': 11,
        'σ': 7,
        'τ': 1,
        'υ': 12,
        'χ': 23,
        'ω': 22,
        'ό': 16,
        'ύ': 25,
    },
    'Hebrew': {
        'א': 8,
        'ב': 5,
        'ג': 19,
        'ד': 13,
        'ה': 2,
        'ו': 1,
        'ז': 23,
        'ח': 15,
        'ט': 20,
        'י': 0,
        'ך': 24,
        'כ': 18,
        'ל': 3,
        'ם': 12,
        'מ': 7,
        'ן': 22,
        'נ': 10,
        'ס': 17,
        'ע': 11,
        'פ': 16,
        'צ': 21,
        'ק': 14,
        'ר': 4,
        'ש': 9,
        'ת': 6,
    },
    'Hindi': {
        'अ': 17,
        'इ': 25,
        'ए': 18,
        'क': 0,
        'ग': 13,
        'च': 22,
        'ज': 11,
        'ट': 16,
        'ड': 21,
        'त': 4,
        'थ': 19,
        'द': 12,
        'ध': 23,
        'न': 3,
        'प': 7,
        'ब': 14,
        'भ': 20,
        'म': 5,
        'य': 8,
        'र': 1,
        'ल': 9,
        'व': 10,
        'श': 15,
        'ष': 24,
        'स': 2,
        'ह': 6,
    },
    'Hungarian': {
        'a': 1,
        'b': 15,
        'c': 25,
        'd': 18,
        'e': 0,
        'f': 24,
        'g': 13,
        'h': 19,
        'i': 8,
        'j': 22,
        'k': 6,
        'l': 3,
        'm': 14,
        'n': 5,
        'o': 9,
        'p': 21,
        'r': 7,
        's': 4,
        't': 2,
        'u': 20,
        'v': 17,
        'y': 16,
        'z': 10,
        'á': 11,
        'é': 12,
        'ö': 23,
    },
    'Indonesian': {
        'a': 0,
        'b': 14,
        'c': 19,
        'd': 8,
        'e': 2,
        'f': 21,
        'g': 12,
        'h': 16,
        'i': 3,
        'j': 18,
        'k': 9,
        'l': 11,
        'm': 10,
        'n': 1,
        'o': 15,
        'p': 13,
        'q': 25,
        'r': 4,
        's': 7,
        't': 5,
        'u': 6,
        'v': 22,
        'w': 20,
        'x': 24,
        'y': 17,
        'z': 23,
    },
    'Italian': {
        'a': 2,
        'b': 17,
        'c': 9,
        'd': 10,
        'e': 0,
        'f': 16,
        'g': 14,
        'h': 19,
        'i': 1,
        'k': 23,
        'l': 5,
        'm': 13,
        'n': 4,
        'o': 3,
        'p': 12,
        'q': 20,
        'r': 7,
        's': 8,
        't': 6,
        'u': 11,
        'v': 15,
        'y': 24,
        'z': 18,
        'à': 22,
        'è': 21,
        'ò': 25,
    },
    'Japanese': {
        '一': 1,
        '七': 40,
        '万': 66,
        '三': 11,
        '上': 22,
        '下': 36,
        '中': 8,
        '九': 27,
        '二': 6,
        '五': 20,
        '人': 2,
        '今': 25,
        '休': 76,
        '何': 64,
        '先': 48,
        '入': 28,
        '八': 34,
        '六': 35,
        '円': 31,
        '出': 10,
        '分': 16,
        '前': 18,
        '北': 44,
        '十': 5,
        '千': 51,
        '午': 45,
        '半': 53,
        '南': 65,
        '友': 74,
        '右': 72,
        '名': 49,
        '四': 24,
        '土': 59,
        '外': 33,
        '大': 4,
        '天': 69,
        '女': 43,
        '子': 32,
        '学': 29,
        '小': 39,
        '山': 41,
        '川': 50,
        '左': 75,
        '年': 3,
        '後': 17,
        '日': 0,
        '時': 12,
        '書': 47,
        '月': 15,
        '木': 60,
        '本': 7,
        '来': 37,
        '東': 23,
        '校': 57,
        '母': 70,
        '毎': 67,
        '気': 38,
        '水': 52,
        '火': 71,
        '父': 77,
        '生': 19,
        '男': 54,
        '白': 68,
        '百': 46,
        '聞': 61,
        '行': 13,
        '西': 55,
        '見': 14,
        '話': 42,
        '語': 58,
        '読': 73,
        '車': 63,
        '金': 26,
        '長': 9,
        '間': 21,
        '雨': 78,
        '電': 56,
        '食': 62,
        '高': 30,
    },
    'Japanese—': {
        '゠': 89,
        'ァ': 58,
        'ア': 8,
        'ィ': 22,
        'イ': 7,
        'ゥ': 78,
        'ウ': 31,
        'ェ': 46,
        'エ': 38,
        'ォ': 70,
        'オ': 27,
        'カ': 19,
        'ガ': 51,
        'キ': 41,
        'ギ': 66,
        'ク': 11,
        'グ': 23,
        'ケ': 64,
        'ゲ': 69,
        'コ': 28,
        'ゴ': 65,
        'サ': 33,
        'ザ': 67,
        'シ': 13,
        'ジ': 15,
        'ス': 2,
        'ズ': 42,
        'セ': 49,
        'ゼ': 76,
        'ソ': 56,
        'ゾ': 79,
        'タ': 16,
        'ダ': 43,
        'チ': 40,
        'ヂ': 81,
        'ッ': 10,
        'ツ': 53,
        'ヅ': 83,
        'テ': 20,
        'デ': 29,
        'ト': 5,
        'ド': 12,
        'ナ': 35,
        'ニ': 30,
        'ヌ': 77,
        'ネ': 54,
        'ノ': 57,
        'ハ': 48,
        'バ': 24,
        'パ': 44,
        'ヒ': 72,
        'ビ': 34,
        'ピ': 63,
        'フ': 17,
        'ブ': 36,
        'プ': 26,
        'ヘ': 75,
        'ベ': 50,
        'ペ': 62,
        'ホ': 68,
        'ボ': 55,
        'ポ': 61,
        'マ': 21,
        'ミ': 45,
        'ム': 25,
        'メ': 32,
        'モ': 52,
        'ャ': 37,
        'ヤ': 71,
        'ュ': 39,
        'ユ': 73,
        'ョ': 47,
        'ヨ': 74,
        'ラ': 9,
        'リ': 6,
        'ル': 4,
        'レ': 14,
        'ロ': 18,
        'ヮ': 87,
        'ワ': 60,
        'ヰ': 86,
        'ヱ': 85,
        'ヲ': 82,
        'ン': 1,
        'ヴ': 59,
        'ヵ': 84,
        'ヶ': 80,
        'ヷ': 91,
        'ヸ': 93,
        'ヹ': 94,
        'ヺ': 95,
        '・': 3,
        'ー': 0,
        'ヽ': 88,
        'ヾ': 90,
        'ヿ': 92,
    },
    'Japanese——': {
        'ぁ': 74,
        'あ': 20,
        'ぃ': 73,
        'い': 7,
        'ぅ': 80,
        'う': 24,
        'ぇ': 75,
        'え': 36,
        'ぉ': 79,
        'お': 30,
        'か': 14,
        'が': 11,
        'き': 27,
        'ぎ': 61,
        'く': 25,
        'ぐ': 60,
        'け': 31,
        'げ': 49,
        'こ': 22,
        'ご': 56,
        'さ': 16,
        'ざ': 65,
        'し': 6,
        'じ': 42,
        'す': 19,
        'ず': 46,
        'せ': 41,
        'ぜ': 68,
        'そ': 32,
        'ぞ': 66,
        'た': 3,
        'だ': 34,
        'ち': 39,
        'ぢ': 78,
        'っ': 17,
        'つ': 33,
        'づ': 64,
        'て': 10,
        'で': 9,
        'と': 4,
        'ど': 37,
        'な': 12,
        'に': 1,
        'ぬ': 67,
        'ね': 58,
        'の': 0,
        'は': 5,
        'ば': 43,
        'ぱ': 69,
        'ひ': 52,
        'び': 45,
        'ぴ': 72,
        'ふ': 59,
        'ぶ': 55,
        'ぷ': 71,
        'へ': 44,
        'べ': 51,
        'ぺ': 76,
        'ほ': 48,
        'ぼ': 62,
        'ぽ': 70,
        'ま': 23,
        'み': 40,
        'む': 50,
        'め': 29,
        'も': 21,
        'ゃ': 57,
        'や': 35,
        'ゅ': 63,
        'ゆ': 54,
        'ょ': 53,
        'よ': 26,
        'ら': 15,
        'り': 18,
        'る': 2,
        'れ': 13,
        'ろ': 47,
        'ゎ': 86,
        'わ': 38,
        'ゐ': 81,
        'ゑ': 83,
        'を': 8,
        'ん': 28,
        'ゔ': 87,
        'ゕ': 91,
        'ゖ': 92,
        '゙': 90,
        '゚': 88,
        '゛': 84,
        '゜': 85,
        'ゝ': 82,
        'ゞ': 77,
        'ゟ': 89,
    },
    'Kazakh': {
        'а': 0,
        'б': 14,
        'г': 24,
        'д': 8,
        'е': 2,
        'ж': 18,
        'з': 20,
        'и': 15,
        'й': 22,
        'к': 12,
        'л': 6,
        'м': 10,
        'н': 3,
        'о': 13,
        'п': 23,
        'р': 5,
        'с': 9,
        'т': 4,
        'у': 16,
        'ш': 21,
        'ы': 1,
        'і': 7,
        'ғ': 17,
        'қ': 11,
        'ң': 19,
        'ө': 25,
    },
    'Korean': {
        '가': 8,
        '고': 9,
        '기': 14,
        '년': 16,
        '는': 4,
        '다': 1,
        '대': 17,
        '도': 22,
        '로': 5,
        '를': 20,
        '리': 21,
        '사': 18,
        '서': 11,
        '스': 24,
        '시': 19,
        '에': 2,
        '으': 15,
        '은': 13,
        '을': 7,
        '의': 3,
        '이': 0,
        '인': 23,
        '일': 25,
        '지': 10,
        '하': 6,
        '한': 12,
    },
    'Lithuanian': {
        'a': 1,
        'b': 18,
        'c': 23,
        'd': 14,
        'e': 5,
        'g': 16,
        'i': 0,
        'j': 15,
        'k': 9,
        'l': 11,
        'm': 10,
        'n': 7,
        'o': 3,
        'p': 12,
        'r': 4,
        's': 2,
        't': 6,
        'u': 8,
        'v': 13,
        'y': 19,
        'ą': 24,
        'ė': 17,
        'į': 25,
        'š': 21,
        'ų': 20,
        'ž': 22,
    },
    'Norwegian': {
        'a': 4,
        'b': 17,
        'c': 23,
        'd': 9,
        'e': 0,
        'f': 14,
        'g': 10,
        'h': 18,
        'i': 6,
        'j': 21,
        'k': 11,
        'l': 8,
        'm': 12,
        'n': 2,
        'o': 7,
        'p': 15,
        'r': 1,
        's': 5,
        't': 3,
        'u': 16,
        'v': 13,
        'w': 25,
        'y': 20,
        'å': 19,
        'æ': 24,
        'ø': 22,
    },
    'Polish': {
        'a': 0,
        'b': 21,
        'c': 9,
        'd': 13,
        'e': 3,
        'g': 20,
        'h': 22,
        'i': 1,
        'j': 18,
        'k': 11,
        'l': 17,
        'm': 15,
        'n': 4,
        'o': 2,
        'p': 14,
        'r': 5,
        's': 8,
        't': 10,
        'u': 16,
        'w': 7,
        'y': 12,
        'z': 6,
        'ó': 25,
        'ą': 23,
        'ę': 24,
        'ł': 19,
    },
    'Portuguese': {
        'a': 0,
        'b': 16,
        'c': 11,
        'd': 6,
        'e': 1,
        'f': 17,
        'g': 14,
        'h': 18,
        'i': 4,
        'l': 12,
        'm': 9,
        'n': 7,
        'o': 2,
        'p': 13,
        'q': 20,
        'r': 5,
        's': 3,
        't': 8,
        'u': 10,
        'v': 15,
        'z': 24,
        'á': 23,
        'ã': 19,
        'ç': 22,
        'é': 21,
        'í': 25,
    },
    'Romanian': {
        'a': 2,
        'b': 19,
        'c': 9,
        'd': 11,
        'e': 0,
        'f': 15,
        'g': 18,
        'h': 23,
        'i': 1,
        'j': 25,
        'l': 7,
        'm': 13,
        'n': 4,
        'o': 8,
        'p': 12,
        'r': 3,
        's': 10,
        't': 5,
        'u': 6,
        'v': 16,
        'z': 22,
        'â': 24,
        'î': 17,
        'ă': 14,
        'ș': 20,
        'ț': 21,
    },
    'Russian': {
        'а': 2,
        'б': 19,
        'в': 8,
        'г': 15,
        'д': 12,
        'е': 1,
        'ж': 24,
        'з': 18,
        'и': 3,
        'й': 20,
        'к': 10,
        'л': 9,
        'м': 11,
        'н': 4,
        'о': 0,
        'п': 13,
        'р': 7,
        'с': 6,
        'т': 5,
        'у': 14,
        'х': 23,
        'ц': 25,
        'ч': 22,
        'ы': 17,
        'ь': 21,
        'я': 16,
    },
    'Serbian': {
        'a': 19,
        'e': 21,
        'i': 20,
        'n': 23,
        'o': 22,
        'а': 0,
        'б': 18,
        'в': 11,
        'г': 16,
        'д': 12,
        'е': 3,
        'з': 17,
        'и': 1,
        'к': 9,
        'л': 15,
        'м': 13,
        'н': 4,
        'о': 2,
        'п': 14,
        'р': 5,
        'с': 6,
        'т': 8,
        'у': 7,
        'ц': 24,
        'ш': 25,
        'ј': 10,
    },
    'Slovak': {
        'a': 1,
        'b': 18,
        'c': 15,
        'd': 11,
        'e': 2,
        'h': 16,
        'i': 4,
        'j': 17,
        'k': 10,
        'l': 9,
        'm': 12,
        'n': 3,
        'o': 0,
        'p': 13,
        'r': 5,
        's': 8,
        't': 7,
        'u': 14,
        'v': 6,
        'y': 21,
        'z': 19,
        'á': 20,
        'é': 25,
        'í': 23,
        'ý': 22,
        'č': 24,
    },
    'Slovene': {
        'a': 1,
        'b': 17,
        'c': 21,
        'd': 12,
        'e': 0,
        'f': 24,
        'g': 18,
        'h': 19,
        'i': 2,
        'j': 9,
        'k': 11,
        'l': 7,
        'm': 14,
        'n': 4,
        'o': 3,
        'p': 13,
        'r': 5,
        's': 6,
        't': 8,
        'u': 15,
        'v': 10,
        'y': 25,
        'z': 16,
        'č': 20,
        'š': 22,
        'ž': 23,
    },
    'Spanish': {
        'a': 1,
        'b': 14,
        'c': 10,
        'd': 8,
        'e': 0,
        'f': 17,
        'g': 15,
        'h': 20,
        'i': 6,
        'j': 23,
        'l': 7,
        'm': 12,
        'n': 3,
        'o': 2,
        'p': 13,
        'q': 21,
        'r': 5,
        's': 4,
        't': 9,
        'u': 11,
        'v': 16,
        'y': 18,
        'z': 24,
        'á': 25,
        'í': 22,
        'ó': 19,
    },
    'Swedish': {
        'a': 1,
        'b': 20,
        'c': 19,
        'd': 8,
        'e': 0,
        'f': 15,
        'g': 12,
        'h': 14,
        'i': 6,
        'j': 24,
        'k': 11,
        'l': 7,
        'm': 10,
        'n': 2,
        'o': 9,
        'p': 17,
        'r': 3,
        's': 5,
        't': 4,
        'u': 16,
        'v': 13,
        'x': 25,
        'y': 23,
        'ä': 18,
        'å': 22,
        'ö': 21,
    },
    'Tamil': {
        'அ': 16,
        'ஆ': 17,
        'இ': 14,
        'உ': 21,
        'எ': 20,
        'ஒ': 22,
        'க': 0,
        'ங': 19,
        'ச': 12,
        'ட': 3,
        'ண': 15,
        'த': 1,
        'ந': 13,
        'ன': 7,
        'ப': 2,
        'ம': 5,
        'ய': 10,
        'ர': 4,
        'ற': 9,
        'ல': 6,
        'ள': 11,
        'ழ': 18,
        'வ': 8,
        'ஸ': 23,
    },
    'Thai': {
        'ก': 4,
        'ข': 24,
        'ค': 18,
        'ง': 6,
        'จ': 21,
        'ช': 23,
        'ด': 11,
        'ต': 14,
        'ท': 12,
        'น': 1,
        'บ': 17,
        'ป': 16,
        'พ': 22,
        'ม': 7,
        'ย': 8,
        'ร': 2,
        'ล': 9,
        'ว': 10,
        'ส': 13,
        'ห': 19,
        'อ': 3,
        'ะ': 15,
        'า': 0,
        'เ': 5,
        'แ': 20,
        'ใ': 25,
    },
    'Turkish': {
        'a': 0,
        'b': 15,
        'c': 22,
        'd': 8,
        'e': 1,
        'g': 19,
        'h': 21,
        'i': 2,
        'k': 7,
        'l': 5,
        'm': 11,
        'n': 3,
        'o': 14,
        'p': 23,
        'r': 4,
        's': 10,
        't': 9,
        'u': 13,
        'v': 18,
        'y': 12,
        'z': 20,
        'ç': 24,
        'ü': 16,
        'ğ': 25,
        'ı': 6,
        'ş': 17,
    },
    'Ukrainian': {
        'а': 1,
        'б': 19,
        'в': 6,
        'г': 20,
        'д': 13,
        'е': 8,
        'з': 16,
        'и': 4,
        'й': 21,
        'к': 10,
        'л': 11,
        'м': 14,
        'н': 2,
        'о': 0,
        'п': 15,
        'р': 5,
        'с': 9,
        'т': 7,
        'у': 12,
        'х': 23,
        'ц': 24,
        'ч': 22,
        'ь': 18,
        'я': 17,
        'і': 3,
        'ї': 25,
    },
    'Vietnamese': {
        'a': 6,
        'b': 18,
        'c': 4,
        'd': 21,
        'e': 15,
        'g': 5,
        'h': 1,
        'i': 3,
        'k': 23,
        'l': 10,
        'm': 9,
        'n': 0,
        'o': 7,
        'p': 17,
        'r': 11,
        's': 14,
        't': 2,
        'u': 8,
        'v': 16,
        'y': 19,
        'à': 12,
        'á': 22,
        'đ': 13,
        'ư': 20,
        'ế': 25,
        'ộ': 24,
    },
}

_FREQUENCIES_SET = {
    'Arabic': frozenset({'?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'}),
    'Bulgarian': frozenset({'?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'}),
    'Chinese': frozenset({'?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'}),
    'Croatian': frozenset({'n', 'd', 'a', '?', '?', 'r', '?', 'h', 'f', 'e', 'u', 'l', 'b', 'm', 's', 'c', 'z', 'o', '?', 'g', 't', 'j', 'v', 'k', 'i', 'p'}),
    'Czech': frozenset({'n', 'd', 'a', '?', '?', 'r', '?', '?', 'h', '?', 'e', 'u', 'l', 'b', 'm', 's', 'c', 'z', 'o', 't', 'j', 'v', 'k', 'i', 'p', 'y'}),
    'Danish': frozenset({'n', 'd', 'a', 'r', 'h', '?', 'f', 'e', 'u', 'l', 'b', 'm', 's', 'c', 'o', '?', '?', 'g', 't', 'j', 'w', 'v', 'k', 'i', 'p', 'y'}),
    'Dutch': frozenset({'n', 'd', 'a', 'r', 'h', '?', 'f', 'x', 'e', 'u', 'l', 'b', 'm', 's', 'c', 'z', 'o', 'g', 't', 'j', 'w', 'v', 'k', 'i', 'p', 'y'}),
    'English': frozenset({'n', 'd', 'a', 'r', 'h', 'f', 'x', 'e', 'u', 'l', 'b', 'm', 's', 'c', 'z', 'o', 'q', 'g', 't', 'j', 'w', 'v', 'k', 'i', 'p', 'y'}),
    'English—': '<value is a self-reference, replaced by this string>',
    'Estonian': frozenset({'n', '?', 'd', 'a', 'r', 'h', 'f', 'e', '?', 'u', 'l', 'b', 'm', 's', 'c', '?', 'o', 'g', 't', 'j', 'v', 'k', '?', 'i', 'p', 'y'}),
    'Farsi': frozenset({'?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'}),
    'Finnish': frozenset({'n', 'd', 'a', 'r', 'h', 'f', 'e', '?', 'u', 'l', 'b', 'm', 's', 'c', 'z', 'o', 'g', 't', 'j', 'w', 'v', 'k', '?', 'i', 'p', 'y'}),
    'French': frozenset({'n', 'd', 'a', 'r', '?', 'h', '?', 'f', 'x', 'e', 'u', 'l', 'b', 'm', 's', 'c', 'o', 'q', 'g', 't', 'j', 'v', '?', 'i', 'p', 'y'}),
    'German': frozenset({'n', 'd', 'a', 'r', 'h', 'f', 'e', '?', 'u', 'l', 'b', 'm', 's', 'c', 'z', '?', 'o', 'g', 't', 'j', 'w', 'v', 'k', '?', 'i', 'p'}),
    'Greek': frozenset({'?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'}),
    'Hebrew': frozenset({'?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'}),
    'Hindi': frozenset({'?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'}),
    'Hungarian': frozenset({'n', 'd', 'a', 'r', '?', '?', 'h', 'f', 'e', '?', 'u', 'l', 'b', 'm', 's', 'c', 'z', 'o', 'g', 't', 'j', 'v', 'k', 'i', 'p', 'y'}),
    'Indonesian': '<value is a self-reference, replaced by this string>',
    'Italian': frozenset({'n', 'd', 'a', 'r', 'h', '?', 'f', 'e', 'u', 'l', 'b', 'm', 's', 'c', 'z', 'o', 'q', '?', 'g', 't', 'v', 'k', '?', 'i', 'p', 'y'}),
    'Japanese': frozenset({'?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'}),
    'Japanese—': frozenset({'?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'}),
    'Japanese——': frozenset({'?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'}),
    'Kazakh': frozenset({'?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'}),
    'Korean': frozenset({'?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'}),
    'Lithuanian': frozenset({'n', 'd', 'a', '?', '?', 'r', '?', '?', 'e', 'u', 'l', 'b', 'm', 's', 'c', 'o', '?', 'g', 't', 'j', 'v', 'k', 'i', '?', 'p', 'y'}),
    'Norwegian': '<value is a self-reference, replaced by this string>',
    'Polish': frozenset({'n', 'd', 'a', '?', 'r', '?', '?', 'h', 'e', 'u', '?', 'l', 'b', 'm', 's', 'c', 'z', 'o', 'g', 't', 'j', 'w', 'k', 'i', 'p', 'y'}),
    'Portuguese': frozenset({'n', 'd', 'a', 'r', '?', '?', '?', 'h', '?', 'f', 'e', 'u', '?', 'l', 'b', 'm', 's', 'c', 'z', 'o', 'q', 'g', 't', 'v', 'i', 'p'}),
    'Romanian': frozenset({'n', 'd', 'a', 'r', '?', 'h', 'f', 'e', 'u', 'l', '?', 'b', 'm', 's', 'c', 'z', '?', 'o', '?', 'g', 't', 'j', 'v', 'i', 'p', '?'}),
    'Russian': frozenset({'?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'}),
    'Serbian': frozenset({'n', '?', '?', '?', 'a', '?', '?', '?', '?', '?', '?', '?', 'e', '?', '?', '?', '?', '?', '?', '?', '?', 'o', 'i', '?', '?', '?'}),
    'Slovak': frozenset({'n', 'd', 'a', 'r', '?', '?', 'h', '?', 'e', '?', 'u', 'l', 'b', 'm', 's', 'c', 'z', 'o', '?', 't', 'j', 'v', 'k', 'i', 'p', 'y'}),
    'Slovene': frozenset({'n', 'd', 'a', '?', 'r', '?', 'h', 'f', 'e', 'u', 'l', 'b', 'm', 's', 'c', 'z', 'o', '?', 'g', 't', 'j', 'v', 'k', 'i', 'p', 'y'}),
    'Spanish': frozenset({'n', 'd', 'a', '?', 'r', '?', 'h', '?', 'f', 'e', 'u', 'l', 'b', 'm', 's', 'c', 'z', 'o', 'q', 'g', 't', 'j', 'v', 'i', 'p', 'y'}),
    'Swedish': frozenset({'n', 'd', 'a', 'r', 'h', 'f', 'x', 'e', '?', 'u', 'l', 'b', 'm', 's', 'c', 'o', '?', 'g', 't', 'j', 'v', 'k', '?', 'i', 'p', 'y'}),
    'Tamil': frozenset({'?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'}),
    'Thai': frozenset({'?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'}),
    'Turkish': frozenset({'n', '?', '?', 'a', 'd', 'r', '?', '?', 'h', 'e', 'u', 'l', 'b', 'm', 's', 'c', '?', 'z', 'o', 'g', 't', 'v', 'k', 'i', 'p', 'y'}),
    'Ukrainian': frozenset({'?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'}),
    'Vietnamese': frozenset({'n', 'd', 'a', 'r', '?', 'h', '?', 'e', '?', 'u', 'l', '?', 'b', '?', 'm', 's', 'c', 'o', 'g', 't', 'v', 'k', '?', 'i', 'p', 'y'}),
}

__loader__ = None # (!) real value is '<_frozen_importlib_external.ExtensionFileLoader object at 0x000001C88C2B2470>'

__spec__ = None # (!) real value is "ModuleSpec(name='charset_normalizer.cd', loader=<_frozen_importlib_external.ExtensionFileLoader object at 0x000001C88C2B2470>, origin='C:\\\\Users\\\\T14\\\\PyCharmMiscProject\\\\.venv\\\\Lib\\\\site-packages\\\\charset_normalizer\\\\cd.cp314-win_amd64.pyd')"

